package com.mycompany.restful.model;
// Generated 05.05.2016 17:06:09 by Hibernate Tools 4.3.1



/**
 * Feature generated by hbm2java
 */
public class Feature  implements java.io.Serializable {


     private Integer id;
     private String renderingEngine;
     private String browser;
     private String platform;
     private String engineVersion;
     private String cssGrade;

    public Feature() {
    }

    public Feature(String renderingEngine, String browser, String platform, String engineVersion, String cssGrade) {
       this.renderingEngine = renderingEngine;
       this.browser = browser;
       this.platform = platform;
       this.engineVersion = engineVersion;
       this.cssGrade = cssGrade;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getRenderingEngine() {
        return this.renderingEngine;
    }
    
    public void setRenderingEngine(String renderingEngine) {
        this.renderingEngine = renderingEngine;
    }
    public String getBrowser() {
        return this.browser;
    }
    
    public void setBrowser(String browser) {
        this.browser = browser;
    }
    public String getPlatform() {
        return this.platform;
    }
    
    public void setPlatform(String platform) {
        this.platform = platform;
    }
    public String getEngineVersion() {
        return this.engineVersion;
    }
    
    public void setEngineVersion(String engineVersion) {
        this.engineVersion = engineVersion;
    }
    public String getCssGrade() {
        return this.cssGrade;
    }
    
    public void setCssGrade(String cssGrade) {
        this.cssGrade = cssGrade;
    }




}


